'This file autogenerated from the bind-builder tool.
'The following keycode file used to generate it:
{INFO}

Class SimpleInputBind
	Global initialized:Bool
	Global codes:= New StringMap<Int>
	Global names:= New IntMap<String>
	
	Function Init:Void()
{MAPPINGS}

		initialized = True
	End Function
End Class